# Generated by Django 2.0b1 on 2017-10-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('host', models.CharField(choices=[('http://192.168.3.20:8080', '麦芽_STB'), ('http://192.168.3.20:8080', '麦芽_SIT'), ('http://192.168.3.20:8080', '麦芽_PRE'), ('http://192.168.3.20:8080', '麦芽_PRD'), ('http://192.168.3.20:8080', '征信_STB'), ('http://192.168.3.20:8080', '征信_PRD')], max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('system_belong', models.IntegerField(choices=[(1, '麦芽APP'), (2, '麦芽后台'), (3, '征信平台'), (4, '反欺诈平台'), (5, '贷后系统')])),
                ('method', models.CharField(choices=[('POST', 'POST请求'), ('GET', 'GET请求')], max_length=20)),
                ('header', models.CharField(max_length=200)),
                ('json_data', models.CharField(max_length=2000)),
                ('params', models.CharField(max_length=2000)),
                ('checkpoint', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('response_data', models.CharField(max_length=999999999)),
                ('is_pass', models.BooleanField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaceTest.InterfaceModel')),
            ],
        ),
    ]
