# Generated by Django 2.0b1 on 2017-10-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacemodel',
            name='json_data',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='interfacemodel',
            name='params',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
