# Generated by Django 2.0b1 on 2017-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0003_auto_20171027_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacemodel',
            name='scene_comment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
