# Generated by Django 2.0b1 on 2017-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0005_auto_20171101_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='interface',
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='interface',
            field=models.ManyToManyField(to='interfaceTest.InterfaceModel'),
        ),
    ]
