# Generated by Django 2.0b1 on 2017-11-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0006_auto_20171101_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.CharField(max_length=999999999)),
                ('is_pass', models.BooleanField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaceTest.InterfaceModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='response_data',
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaceTest.ResultModel'),
        ),
    ]
