# Generated by Django 2.0b1 on 2017-11-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0007_auto_20171101_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacetestresult',
            name='interface',
        ),
    ]
