# Generated by Django 2.0b1 on 2017-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0009_auto_20171107_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacemodel',
            name='host',
            field=models.CharField(choices=[('http://192.168.3.20:8081', '麦芽_STB'), ('http://192.168.3.20:8082', '麦芽_SIT'), ('http://192.168.3.20:8083', '麦芽_PRE'), ('http://192.168.3.20:8084', '麦芽_PRD'), ('http://192.168.3.20:8080', '征信_STB'), ('https://scbgw.pre.nonobank.com', '征信_PRE'), ('https://scbgw.nonobank.com', '征信_PRD')], max_length=200),
        ),
    ]
