# Generated by Django 2.0b1 on 2017-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceTest', '0011_auto_20171114_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacetestresult',
            name='interfaceModel',
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_checkpoint',
            field=models.CharField(default={}, max_length=1000),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_host',
            field=models.CharField(choices=[('http://192.168.3.20:8081', '麦芽_STB'), ('http://192.168.3.20:8082', '麦芽_SIT'), ('http://192.168.3.20:8083', '麦芽_PRE'), ('http://192.168.3.20:8084', '麦芽_PRD'), ('http://192.168.3.20:8080', '征信_STB'), ('https://scbgw.pre.nonobank.com', '征信_PRE'), ('https://scbgw.nonobank.com', '征信_PRD')], default=('http://192.168.3.20:8081', '麦芽_STB'), max_length=200),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_json_data',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_method',
            field=models.CharField(choices=[(1, '麦芽APP'), (2, '麦芽后台'), (3, '征信平台'), (4, '反欺诈平台'), (5, '贷后系统')], default=(1, '麦芽APP'), max_length=20),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_params',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interfacetestresult',
            name='inter_scene_comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interfacemodel',
            name='checkpoint',
            field=models.CharField(default={}, max_length=1000),
        ),
    ]
